name: Hooligan Productions
favicon: null
layout_spectrum: 0.47267526760697365
typography_spectrum: 0.49803476338274777
title: Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1919'
    - '#dfe4e1'
    - '#d8232a'
    - '#939796'
    - '#4a4b4b'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
